package weatherclient2;

import com.weather.WeatherWS;
import com.weather.WeatherWSService;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class wather extends javax.swing.JFrame {

    /** Creates new form wather */
    public wather() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String[] args) {
        // إنشاء إطار التطبيق
        final JFrame frame = new JFrame("Weather Client");
        frame.setSize(400, 250);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLayout(new BorderLayout());

        // إنشاء حقل الإدخال وزر البحث
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());
        JLabel label = new JLabel("Enter City:");
        final JTextField cityField = new JTextField(15);
        JButton getWeatherButton = new JButton("Get Weather");
        panel.add(label);
        panel.add(cityField);
        panel.add(getWeatherButton);

        // منطقة عرض البيانات
        final JTextArea resultArea = new JTextArea(5, 30);
        resultArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(resultArea);

        // إضافة العناصر إلى النافذة
        frame.add(panel, BorderLayout.NORTH);
        frame.add(scrollPane, BorderLayout.CENTER);

        // الحدث عند النقر على زر البحث
        getWeatherButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String city = cityField.getText().trim();
                if (city.isEmpty()) {
                    JOptionPane.showMessageDialog(frame, "Please enter a city name.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                try {
                    WeatherWSService service = new WeatherWSService();
                    WeatherWS port = service.getWeatherWSPort();
                    String weatherData = port.getWeather(city);
                    resultArea.setText("Weather Data for " + city + ":\n" + weatherData);
                } catch (Exception ex) {
                    resultArea.setText("Error retrieving weather data: " + ex.getMessage());
                }
            }
        });

        // إظهار النافذة
        frame.setVisible(true);
    }




    /**
    * @param args the command line arguments
    */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
